### ISSUE TITLE
Unable to generate multiple xml files out of json's.

### ISSUE THREAD

**Issue by digvijayah02** [AtomGraph/JSON2XML#2]
This utility is great for converting a single json but I am facing issue while trying to convert multiple json's.
I have a file which contains multiple json's. Every line is a json and I need to generate that many xml files.
Can you tell me what change would be required so that it reads a line converts that to a new XML file?

I have tried:-
OutputStream       outputStream       = new FileOutputStream("Path");
then use - new JsonStreamXMLWriter(reader, new BufferedWriter(new OutputStreamWriter(outputStream))).convert();

But it throws below error:- 
Exception in thread "main" javax.json.stream.JsonParsingException: Expected EOF token, but got CURLYOPEN
at org.glassfish.json.JsonParserImpl.hasNext(JsonParserImpl.java:361)

Attached in the input json file.
[input.txt](https://github.com/AtomGraph/JSON2XML/files/3935029/input.txt)
?

**Comment by namedgraph** [comment]
If I understand right, I think it would be easier to use shell utilities to read the text file line by line and feed each line into JSON2XML, like this:
```bash
#!/bin/bash

count=1
while IFS= read -r line; do
    echo "$line" | docker run -i -a stdin -a stdout -a stderr atomgraph/json2xml > "${count}.xml"
    count=$((count + 1))
done < "input.txt"
```
The script will produce XML files `1.xml`, `2.xml` etc, for each line of JSON.

Note that this requires a newline at the end of `input.txt`, otherwise the last line will not be read.

**Comment by digvijayah02** [comment]
Yeah, shell script would do the trick.
But I was actually looking for a option to do it in java as my entire
requirement is in java.

Also, let me test once by inserting “\n” manually at the end of line.

Do you have any constructor which takes input as string and not InputStream
or Reader?
Actually I have implemented a Spliterator which is taking care of Stream
and batch of streams and then feeding me a line from my text file.

**Comment by namedgraph** [comment]
What is the problem using your `Splinterator` then?

Alternatively, can you read each line into a byte array `byte[]` and construct a `ByteArrayInputStream`?

**Comment by digvijayah02** [comment]
I did some design changes and now getting single json in a single file. This way I would avoid EOF issue and also filename issue.
I am now able to read json files one by one and convert and create xml files.
But after doing that 1 successfull time, it is failing in between with below error:-
Exception in thread "main" javax.json.stream.JsonParsingException: Unexpected char 0 at (line no=1, column no=1, offset=0)
	at org.glassfish.json.JsonTokenizer.unexpectedChar(JsonTokenizer.java:601)
	at org.glassfish.json.JsonTokenizer.nextToken(JsonTokenizer.java:418)
	at org.glassfish.json.JsonParserImpl$NoneContext.getNextEvent(JsonParserImpl.java:426)
	at org.glassfish.json.JsonParserImpl.next(JsonParserImpl.java:376)
	at com.dj.gls.json2xml.JsonStreamXMLWriter.write(JsonStreamXMLWriter.java:142)

Do you have any idea why it might be throwing that?
